title = "iknows"
logo = "https://avatars.githubusercontent.com/u/670440"
base_url = "http://localhost:3000"
about = "lshoo's spaces for anythings"
index_site_pages = ["blog"]

[extra]
copyright = "lshoo"
github = "https://github.com/lshoo"
twitter = "https://twitter.com/lshoo36"

date_style = "%B %e, %Y"
